destination: ../build.ant/documentation/
simplicityRelease: 3.1
jQueryRelease: 1.8.1
jQueryUiRelease: 1.8.23
jQueryUiTheme: base
topnav:
  - nav: home
    label: home
    url: /
  - nav: userguide
    label: userguide
    url: /userguide/
  - nav: download
    label: download
    url: /download.html
  - nav: jsdoc
    label: jsdoc
    url: /jsdoc/
  - nav: changelog
    label: changelog
    url: /changelog.html
pygments: true